name: cadquery-runtime
channels:
  - conda-forge
  - cadquery
dependencies:
  - python=3.12
  # Install the core OCP dependency for CadQuery from conda-forge.
  # These are the runtime dependencies required by the local CadQuery source,
  # as defined in setup.py.
  - ocp>=7.8.1,<7.9
  - ezdxf>=1.3.0
  - multimethod>=1.11,<2.0
  - nlopt>=2.9.0,<3.0
  - typish
  - casadi
  - path
  - pip
  - pip:
    - . # This installs the local CadQuery source code directly into site-packages
